# Generated by Django 5.0.1 on 2024-01-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comapny',
            new_name='Company',
        ),
    ]
